"""Render a model's answer into a source file the build can consume.

The model supplies statements and a write set. Everything around them - the
namespace, the registration macro, the window predicate - is generated here, so
those tokens are never spent and the shape is never wrong.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from ..core.db import addr_str

if TYPE_CHECKING:
    from ..llm.schemas import PortAnswer, Window

TEMPLATE = """\
// {addr_name}{name_suffix}
// STATUS: {status}
// {provenance}
{note_block}namespace port_{hex_addr} {{

REX_FUNC(Native) {{
{body}
}}

bool Windows(PPCContext& ctx, uint8_t* base, PortSpec& spec) {{
{windows}
  return true;
}}

}}  // namespace port_{hex_addr}
{macro}({hex_addr}, {status_enum}, {result_mask})
"""

STATUS_ENUM = {
    "pending": "kPortPending",
    "written": "kPortPending",
    "verified": "kPortVerified",
    "thin": "kPortVerifiedThin",
    "partial": "kPortPartial",
    "gate1": "kPortGate1",
    "gate2": "kPortGate2",
    "gate3": "kPortGate3",
    "gate4": "kPortGate4",
}


@dataclass
class PortArtifact:
    addr: int
    path: Path
    text: str
    symbol: str

    def brief(self) -> str:
        return f"{addr_str(self.addr)}\t{self.path.name}\t{len(self.text)} chars"


def window_expression(w: Window) -> str:
    """The address expression for one declared span.

    A window whose base must be read from memory before the call becomes an
    explicit load, because the oracle has to resolve it while the original state
    is still intact.
    """
    expr = f"ctx.{w.base}.u32"
    for step in w.deref:
        inner = f"{expr} + {step}" if step else expr
        expr = f"REX_LOAD_U32({inner})"
    if w.offset:
        expr = f"{expr} + {w.offset}"
    return expr


def render(answer: PortAnswer, addr: int, macro: str = "SKATE3_PORT",
           status: str = "pending", provenance: str = "") -> str:
    body = _indent(answer.code.strip(), "  ")

    window_lines = []
    for w in answer.windows:
        comment = f"  // {w.why}" if w.why else ""
        window_lines.append(f"  spec.write({window_expression(w)}, {w.length});{comment}")
    if not window_lines:
        window_lines.append("  // no memory writes; the result registers are compared")

    note_block = ""
    if answer.note.strip():
        note_block = "// " + answer.note.strip().replace("\n", " ")[:300] + "\n"

    return TEMPLATE.format(
        addr_name=addr_str(addr),
        name_suffix=f"  {answer.name}" if answer.name else "",
        status=status,
        provenance=provenance or "generated by decomp",
        note_block=note_block,
        hex_addr=f"{addr:08X}",
        body=body,
        windows="\n".join(window_lines),
        macro=macro,
        status_enum=STATUS_ENUM.get(status, "kPortPending"),
        result_mask=_result_mask(answer),
    )


def _result_mask(answer: PortAnswer) -> str:
    """Which registers the oracle compares.

    Comparing everything flags every call as divergent, because scratch
    registers legitimately differ. Comparing nothing passes everything. The
    caller's actual reads are the only useful answer.
    """
    if not answer.result_registers:
        return "kReturnNone"
    parts = []
    for reg in answer.result_registers:
        reg = reg.strip().lower()
        if reg == "r3":
            parts.append("kReturnR3")
        elif reg in ("f1", "fp1"):
            parts.append("kReturnF1")
        elif reg.startswith("r") and reg[1:].isdigit():
            parts.append(f"Gpr({reg[1:]})")
        elif reg.startswith("f") and reg[1:].isdigit():
            parts.append(f"Fpr({reg[1:]})")
        elif reg.startswith("v") and reg[1:].isdigit():
            parts.append(f"Vr({reg[1:]})")
    return " | ".join(parts) if parts else "kReturnNone"


def _indent(text: str, prefix: str) -> str:
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())


def write(answer: PortAnswer, addr: int, out_dir: Path, macro: str = "SKATE3_PORT",
          status: str = "pending", provenance: str = "") -> PortArtifact:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    text = render(answer, addr, macro=macro, status=status, provenance=provenance)
    path = out_dir / f"{addr_str(addr)}.inc"
    path.write_text(text)
    return PortArtifact(addr=addr, path=path, text=text, symbol=f"port_{addr:08X}")
