"""`decomp structs`: the recovered layouts, in and out.

A layout is worth more when it can be checked. The audio project's header
carried a static assertion per offset, so a wrong one failed the build rather
than quietly producing wrong reads for a year. Export writes that form back out,
with the function each offset was read from still attached.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from ..core.db import addr_str

if TYPE_CHECKING:
    from ..core.config import Project

HEADER = """\
/* Recovered structure layouts.
 *
 * Generated by decomp from {project}. Every offset carries the function it was
 * read from. Fields marked proposed have only a model's word behind them and
 * have not been confirmed against the binary.
 *
 * {endian}-endian, {ptr}-byte pointers.
 */
#ifndef DECOMP_STRUCTS_H
#define DECOMP_STRUCTS_H

#include <stdint.h>
#include <stddef.h>

typedef uint{ptr_bits}_t guest_ptr;

"""

FOOTER = """
#endif /* DECOMP_STRUCTS_H */
"""

CHECK_HEADER = """\
/* Offset assertions for the recovered layouts.
 *
 * Compile this. A layout that is wrong fails here rather than producing wrong
 * reads until someone notices.
 */
#include "decomp_structs.h"

#define CHECK(t, f, o) \\
    _Static_assert(offsetof(t, f) == (o), #t "." #f " should be at " #o)

"""

TYPE_WIDTHS = {
    1: "uint8_t", 2: "uint16_t", 4: "uint32_t", 8: "uint64_t",
}

# Width of the types a recovered layout uses, for spotting arrays.
CTYPE_WIDTHS = {
    "uint8_t": 1, "int8_t": 1, "char": 1, "bool": 1,
    "uint16_t": 2, "int16_t": 2, "short": 2,
    "uint32_t": 4, "int32_t": 4, "int": 4, "float": 4,
    "uint64_t": 8, "int64_t": 8, "double": 8,
}


def _width_of(ctype: str, ptr_size: int) -> int:
    if ctype in ("guest_ptr", "rw_ptr"):
        return ptr_size
    return CTYPE_WIDTHS.get(ctype.strip().split()[-1], 0)


@dataclass
class ExportResult:
    header_path: Path | None
    check_path: Path | None
    structs: int = 0
    fields: int = 0
    proposed: int = 0
    text: str = ""

    def brief(self) -> str:
        lines = [
            f"structs\t{self.structs}\tfields\t{self.fields}"
            f"\tproposed\t{self.proposed}",
        ]
        if self.header_path:
            lines.append(f"header\t{self.header_path}")
        if self.check_path:
            lines.append(f"checks\t{self.check_path}")
        if self.proposed:
            lines.append(
                "note\tproposed fields are emitted but not asserted: a static "
                "assertion on a guess would fail the build for the wrong reason"
            )
        return "\n".join(lines)


def export(project: Project, out_dir: Path | str | None = None,
           include_proposed: bool = True, write: bool = True) -> ExportResult:
    """Write the layouts back out as a header, with assertions alongside."""
    target = project.target_row() or {}
    ptr = int(target.get("ptr_size") or 4)
    parts = [HEADER.format(
        project=project.get("project.name", "this project"),
        endian=(target.get("endian") or "big").capitalize(),
        ptr=ptr, ptr_bits=ptr * 8,
    )]
    checks = [CHECK_HEADER]

    structs = fields = proposed = 0
    # Extent of each struct as emitted, so a nested field can be sized. Emitted
    # in name order, which is why a struct used inside another is usually
    # already known by the time it is needed.
    extents: dict[str, int] = {}

    for struct in project.db.query("SELECT * FROM struct ORDER BY name"):
        rows = project.db.query(
            "SELECT * FROM struct_field WHERE struct_id=? ORDER BY offset",
            (struct["id"],),
        )
        if not include_proposed:
            rows = [r for r in rows if r["status"] in ("established", "confirmed")]
        if not rows:
            continue

        structs += 1
        cited = _citations(project, struct["id"])
        parts.append(f"/* {struct['name']}")
        if cited:
            parts.append(f" * Read from {', '.join(cited[:4])}.")
        parts.append(" */")
        parts.append("typedef struct {")

        # Offsets are what was measured; sizes are inferred, and a nested
        # struct's inferred size can fall short of the space it actually
        # occupies. So the export lays fields out by offset and pads to the next
        # one, rather than trusting a size to fill the gap. Getting this wrong
        # shifted every field after a nested scheduler by twelve bytes.
        cursor = 0
        for index, row in enumerate(rows):
            offset = row["offset"]
            if offset > cursor:
                parts.append(
                    f"    uint8_t _pad{cursor:02X}[0x{offset - cursor:X}];"
                )
            next_offset = (
                rows[index + 1]["offset"] if index + 1 < len(rows)
                else (struct.get("size") or offset + (row["size"] or 4))
            )
            available = max(1, next_offset - offset)
            ctype = row["ctype"] or TYPE_WIDTHS.get(row["size"] or 4, "uint32_t")
            if ctype == "rw_ptr":
                ctype = "guest_ptr"
            mark = "" if row["status"] in ("established", "confirmed") else "  (proposed)"

            # A field whose recorded size exceeds its type's width is an array.
            # Dropping the dimension would silently shift every offset after it,
            # which the assertions would catch but should never have to.
            width = _width_of(ctype, ptr)
            if not width and ctype in extents:
                # A nested struct: its own extent is the field's size. The
                # recorded size is a default the importer had no way to fill in,
                # because the inner layout was not known when the outer one was
                # parsed.
                width = extents[ctype]
                size = width
            else:
                size = row["size"] or width
            dimension = ""
            if width and size > width and size % width == 0:
                dimension = f"[{size // width}]"

            parts.append(
                f"    {ctype:<12} {row['name']}{dimension};"
                f"  /* +0x{offset:03X}{mark} */"
            )

            # A type of unknown width cannot be laid out safely: emitting it
            # would let the compiler decide its size and shift everything after
            # it. Reserve the measured space instead and name the type in a
            # comment, so the offsets stay true.
            if not width:
                parts.pop()
                parts.append(
                    f"    uint8_t      {row['name']}[0x{available:X}];"
                    f"  /* +0x{offset:03X}  {ctype}{mark} */"
                )

            declared = size if width else available
            if width and declared < available:
                parts.append(
                    f"    uint8_t _gap{offset + declared:02X}"
                    f"[0x{available - declared:X}];  /* unaccounted */"
                )
                declared = available
            if row["status"] in ("established", "confirmed"):
                checks.append(
                    f"CHECK({struct['name']}, {row['name']}, 0x{offset:X});"
                )
            else:
                proposed += 1
            cursor = offset + declared
            fields += 1

        size = struct.get("size") or cursor
        extents[struct["name"]] = max(size, cursor)
        if size > cursor:
            parts.append(f"    uint8_t _pad{cursor:02X}[0x{size - cursor:X}];")
        parts.append(f"}} {struct['name']};")

        # Assert the size only when alignment permits it. A recovered size is
        # the end of the last field, and a struct ending on an odd byte gets
        # padded by the compiler, so asserting it would fail for a reason that
        # has nothing to do with whether the layout is right.
        alignment = max(
            (_width_of(r["ctype"] or "", ptr) or 1 for r in rows), default=1
        )
        if struct.get("size") and size % alignment == 0:
            checks.append(
                f'_Static_assert(sizeof({struct["name"]}) == 0x{struct["size"]:X}, '
                f'"{struct["name"]} size");'
            )
        elif struct.get("size"):
            checks.append(
                f'/* {struct["name"]}: recovered size 0x{size:X} is not a multiple '
                f'of its {alignment}-byte alignment, so the compiler will pad it; '
                f'not asserted. */'
            )
        parts.append("")

    text = "\n".join(parts) + FOOTER
    check_text = "\n".join(checks) + "\n"

    header_path = check_path = None
    if write:
        out = Path(out_dir) if out_dir else project.root / "out"
        out.mkdir(parents=True, exist_ok=True)
        header_path = out / "decomp_structs.h"
        header_path.write_text(text)
        check_path = out / "decomp_structs_check.c"
        check_path.write_text(check_text)

    return ExportResult(
        header_path=header_path, check_path=check_path, structs=structs,
        fields=fields, proposed=proposed, text=text,
    )


def _citations(project: Project, struct_id: int) -> list[str]:
    rows = project.db.query(
        "SELECT DISTINCT fe.function_addr FROM field_evidence fe "
        "JOIN struct_field f ON f.id=fe.field_id "
        "WHERE f.struct_id=? AND fe.function_addr IS NOT NULL "
        "ORDER BY fe.function_addr",
        (struct_id,),
    )
    return [addr_str(r["function_addr"]) for r in rows]


@dataclass
class CheckResult:
    conflicts: list[tuple[str, int, str, str]] = field(default_factory=list)
    overlaps: list[tuple[str, int, str, str]] = field(default_factory=list)
    unevidenced: list[tuple[str, int, str]] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.conflicts and not self.overlaps

    def brief(self) -> str:
        lines = []
        for struct, offset, a, b in self.conflicts:
            lines.append(f"conflict\t{struct}+0x{offset:X}\t{a} vs {b}")
        for struct, offset, a, b in self.overlaps:
            lines.append(f"overlap\t{struct}\t{a} and {b} both cover +0x{offset:X}")
        for struct, offset, name in self.unevidenced[:6]:
            lines.append(f"unevidenced\t{struct}.{name}\t+0x{offset:X}")
        if not lines:
            return "layouts\tconsistent"
        lines.append(
            f"--\t{len(self.conflicts)} conflict(s)\t{len(self.overlaps)} overlap(s)"
            f"\t{len(self.unevidenced)} field(s) with no evidence"
        )
        return "\n".join(lines)


def check(project: Project) -> CheckResult:
    """Look for layouts that disagree with themselves.

    Two established fields claiming one offset means someone read the same bytes
    two ways, and a field that overruns the next one means at least one size is
    wrong. Both are worth knowing before a port is written against them.
    """
    result = CheckResult()
    for struct in project.db.query("SELECT * FROM struct ORDER BY name"):
        rows = project.db.query(
            "SELECT * FROM struct_field WHERE struct_id=? ORDER BY offset",
            (struct["id"],),
        )
        previous = None
        for row in rows:
            if row["status"] == "conflict":
                result.conflicts.append(
                    (struct["name"], row["offset"], row["name"] or "?", "(recorded)")
                )
            has_evidence = project.db.scalar(
                "SELECT COUNT(*) FROM field_evidence WHERE field_id=?", (row["id"],), 0
            )
            if not has_evidence:
                result.unevidenced.append(
                    (struct["name"], row["offset"], row["name"] or "?")
                )
            if previous is not None:
                end = previous["offset"] + (previous["size"] or 4)
                if row["offset"] < end:
                    result.overlaps.append((
                        struct["name"], row["offset"],
                        previous["name"] or "?", row["name"] or "?",
                    ))
            previous = row
    return result
